accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts import forms, views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

helpdeskapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from helpdeskapp import views


app_name = 'helpdeskapp'

urlpatterns = [
    path('',views.home, name='home'),
    path('login/', login_required(TemplateView.as_view(
        template_name='app/index.html')), name='index'),
    path('create-ticket/', views.create_ticket, name='create_ticket'),
    path('view-tickets/', views.ticket_list, name='ticket_list'),
    path('update-ticket/<pk>/', views.update_ticket_User, name='update_ticket_User'),
    path('change-ticket-status/', views.change_ticket_status, name='change_ticket_status'),
    path('grid/<int:pid>/', views.grid, name='grid'),
    path('edit/', views.edit, name='edit'),
    path('option/', views.option, name='option'),
    path('profile/', views.profile, name='profile'),
    path('welcome/',views.welcome,name='welcome'),
    path('history/<int:ticket_id>/',views.ticket_history,name='ticket_history'),
    path('updateRole/', views.updateRole , name="updateRole"),
    path('base/',views.base,name='base')
    
]
 

helpdeskweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdeskapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('engineer/', include('it_engineer.urls')),
    path('manager/', include('it_manager.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/app/edit.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
    <form action="#" method='#' enctype='#' class="p-3">
        <h5>Edit Page</h5>

        <div class="form-group col-md-8">
            <label for="inputtitle">Subject</label>
            <input type="title" class="form-control" id="title" placeholder="Title" name='title'>
        </div><br>
        <div class="form-group col-md-8">
            <label for="inputtitle">Name</label>
            <input type="title" class="form-control" id="title" placeholder="Title" name='title'>
        </div><br>

        <div class="form-group col-md-8">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>

        <div class="form-group col-md-8">
            <label for="inputtitle">Subject</label>
            <input type="title" class="form-control" id="title" placeholder="Title" name='title'>
        </div><br>


        <div class="form-group col-md-8">
            <label for="inputtitle">Contact No</label>
            <input type="text" class="form-control" id="title" placeholder="Please Enter Your Phone number"
                name='contact_number'>
        </div><br>
        <div class="form-group col-md-8">
            <label for="inputState">Priority</label>
            <select id="inputState" class="form-control" name='priority'>
                <option selected>Choose...</option>
                <option>low</i></option>
                <option>medium</i></option>
                <option>high</option>
            </select>
        </div><br>
        <div class="form-group col-md-8">
            <label for="inputState">Department</label>
            <select id="inputState" class="form-control" name='department'>
                <option selected>Choose...</option>
                <option>HR</option>
                <option>Admin</option>
                <option>Tech</option>
            </select>
        </div><br>
        <div class="form-group col-md-8">
            <label for="inputState">Ticket Type</label>
            <select id="inputState" class="form-control" name='ticketType'>
                <option selected>Choose...</option>
                <option>wifi </option>
                <option>printer</option>
                <option>mail</option>
            </select>
        </div><br>
        <div class="form-group col-md-8">
            <label for="inputState">Sub Type</label>
            <select id="inputState" class="form-control" name='ticketSubType'>
                <option selected>Choose...</option>
                <option>range</option>
                <option>connectivity</option>
                <option>wlan</option>
            </select>
        </div><br>
        <div class="form-row">
            <div class="form-group col-md-8">
                <label for="inputCity">Attachment</label>
                <input type="file" class="form-control" id="inputCity" placeholder="Your name.." name='attachment'>
            </div><br>



            <div class="text-center">
                <input class="btn btn-primary" type="submit" value="Submit">
                <input class="btn btn-primary" type="reset" value="Reset">
            </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script scr="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script>
        // ck editor
        CKEDITOR.replace('editor1', {
            height: 300,
            // Configure your file manager integration. This example uses CKFinder 3 for PHP.
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html?type=Images',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
        });
    </script>



</body>

</html>

templates/app/getdata.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="main-panel">
  <div class="content-wrapper bg-white">
    <div class="boxes"> 
      <!-- <div class="filter" id="filter"> -->
        <!-- <button class="btn btn-primary my-3">All Tickets</button>
        <button class="btn btn-primary my-3">Open Tickets 0</button>
        <button class="btn btn-primary my-3">Close Tickets 0</button>
        <button class="btn btn-primary my-3">Resolved Tickets 0</button> -->
        <!-- <div class="one boxx">All Tickets</div>
        <div class="two boxx">Open Tickets 0</div>
        <div class="three boxx">Close Tickets 0</div>
        <div class="four boxx">Resolved Tickets 0</div> -->
      <!-- </div> -->
    </div>
    <div class="table-responsive ">
      <table id="test" class=" table-striped" style="width:100%">
        <thead>
            <tr style="background-color: #9d96ce; color: white;">
                <th>Ticket Id</th>
                <th>Title</th>
                <th>Ticket Type</th>
                <th>Priority</th>
                <th>Department</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
          {% for ticket in tickets %}

            <tr>
                <td><a href="{% url 'helpdeskapp:grid' ticket.id %}" style="text-decoration: none; color: #6C63AC ;">{{ticket.id}}</a></td>
                <td>{{ticket.title}}</td>
                <td>{{ticket.ticketType}}</td>
                <td>{{ticket.priority}}</td>
                <td>{{ticket.department}}</td>
                <td>
                  <div class="icons_list">
                    <!-- view -->
                    <li style="list-style:none;text-decoration: none;">
                      <a href="{% url 'helpdeskapp:grid' ticket.id %}">
                        <i class="fa-solid fa-eye" data-toggle="tooltip" data-placement="bottom" title="View"></i>
                      </a>
                    </li> 
                    <!-- edit -->
                    <li style="list-style:none;text-decoration: none;">
                      <a href="{% url 'helpdeskapp:update_ticket_User' pk=ticket.id %}">
                        <i class="fa-solid fa-pen-to-square" data-toggle="tooltip" data-placement="bottom" title="Edit"></i>
                      </a>
                    </li>
                    <!-- hestory -->
                    <li style="list-style:none;text-decoration: none;">
                      <a href="{% url 'helpdeskapp:ticket_history' ticket.id  %}">
                        <i class="fa-solid fa-clock-rotate-left" data-toggle="tooltip" data-placement="bottom" title="Update"></i>
                      </a>
                    </li>
                  </div>
                </td>
            </tr>
          {% endfor %}

        </tbody>
       
      </table>
    </div>
  </div>

</div>


  {% endblock %}

templates/app/grid.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
  /* #inline1,
  #inline2,
  #inline3,
  #inline4,
  #inline5,
  #inline6 {
    display: inline;
  }

  .btn {
    margin-top: 2rem;
  }

  .fa {
    color: blueviolet;
    font-size: 20px;
  }

  @media (max-width:768px) {
    .ticketdetails {
      margin-top: 20px !important;
    }

  } */

  #inline1,
  #inline2,
  #inline3,
  #inline4,
  #inline5,
  #inline6 {
    display: inline;
  }
  

 .fa

 {

 color: #6C63AC;

 font-size: 22px;

 }

 @media(max-width:768px){

 .ticketdetail{

 margin-top: 20px !important;

 }

 }

 .edit a{

 list-style: none;

 text-decoration: none;

 font-size: 1.1rem;

 color: #6C63AC;

 }

 .print a{

 list-style: none;

 font-size: 1.1rem;

 color: #6C63AC;

 text-decoration: none;

 }

 .dd{
 display:flex;

justify-content: center;

 align-items:center;

 gap: 80px;
 }
</style>
<!-- partial -->
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title"> Ticket Details </h3>
    </div>
    <div class="row">
      <div class="col-md-8 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <form class="forms-sample">
              <div class="row">
                <div class="col-md-3">
                  <h6>Title :-</h6>
                </div>
                <div class="col-md-9">
                 <p>{{viewtickets.title}}</p>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3">
                  <h6>Description :- </h6>
                </div>
                <div class="col-md-9" >
                 <p>{{viewtickets.description}}</p>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3">
                  <h6>Contact :- </h6>
                </div>
                <div class="col-md-9" >
                 <p>{{viewtickets.contact_number}}</p>
                </div>
              </div>
            </form>
          </div>
        </div>

      </div>





      <div class="col-md-4 mb-5">

        <div class="card">

          <div class="card-body d-flex justify-content-center align-items-center">
            <div class="dd">

              <div class="edit">




                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>

                <a id="editticket" href="{% url 'helpdeskapp:update_ticket_User' pk=viewtickets.id %}" title="Edit">
                  Edit

                </a>
              </div>
              <div class="print">

                <i class="fa fa-print" aria-hidden="true"></i>

                <a href="#" onclick="window.print()" title="Print" target="_blank">

                  Print
                </a>
              </div>

            </div>

          </div>

        </div>

      </div>



    
      <div class="col-md-8 grid-margin">
        <div class="card pb-4">
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <h4 class="card-title">Add Reply</h4>
              <br><br>

              <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Message</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="comments"></textarea>
              </div><br><br>
              <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="inputCity" id="form-label" class="form-label">Attachment :</label>
                  <input type="file" class="form-control" id="inputCity" placeholder="Your name.." name='attachment'>
                </div><br>
              </div>
              <input class="btn btn-primary pb-3" type="submit"  value="Submit">
              <!-- <button class="btn">Submit</button> -->
          </div>
        </div>
        </form>
      </div>

      <div class="col-md-4 grid-margin ticketdetails stretch-card" style="margin-top: -90px;">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title mb-5">Ticket Details</h4>
            <div class="boxR">
            

                <div class="row mt-2 my-2" >
                  <div class="col">
                    <p> ID</p>
                  </div>
                  <div class="col">
                   <p>{{viewtickets.id}}</p>
                  </div>
                </div>
  
                <div class="row my-3">
                  <div class="col">
                    <p>Status </p>
                  </div>
                  <div class="col" >
                   <p>{{viewtickets.status}}</p>
                  </div>
                </div>
  
                <div class="row my-2">
                  <div class="col">
                    <p>Attachment</p>
                  </div>
                  <div class="col" >
                   <p><a target="_blank" href="{{viewtickets.attachment.url}}" style="color: #6C63AC;">
                    Preview</a></p>
                  </div>
                </div>


                <div class="row my-2">
                  <div class="col">
                    <p>Department </p>
                  </div>
                  <div class="col" >
                   <p>{{viewtickets.department}}</p>
                  </div>
                </div>

                <div class="row">
                  <div class="col">
                    <p> Priority </p>
                  </div>
                  <div class="col" >
                   <p>{{viewtickets.priority}}</p>
                  </div>
                </div>



                <div class="row">
                  <div class="col">
                    
                {% if viewtickets.status == 'open' %}
                <form action="{% url 'helpdeskapp:change_ticket_status' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" value="closed" name="status">
                  <input type="hidden" value="{{viewtickets.id}}" name="ticket_id">
                  <button type="submit" class="btn btn-primary my-4 ">Close</button>
                </form>
                {% elif viewtickets.status == 'closed' %}
                <form action="{% url 'helpdeskapp:change_ticket_status' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" value="open" name="status">
                  <input type="hidden" value="{{viewtickets.id}}" name="ticket_id">
                  <button type="submit" class="btn btn-primary my-4">Open Again</button>
                </form>
                {% else %}
                <button type="button" class="btn text-white btn-info my-4">
                  Work in progress..
                </button>
                {% endif %}
                  </div>
                </div>

            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:../../partials/_footer.html -->

          <!-- partial -->
        </div>
      </div>
      <!-- main-panel ends -->
    </div>



    {% endblock %}

templates/app/history.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    #inline1,
    #inline2,
    #inline3,
    #inline4,
    #inline5,
    #inline6 {
      display: inline;
    }
  </style>
<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title">Ticket History</h3>
      </div>
      <div class="row">
        <!-- <div class="col-lg-4 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <p class="text-center">Mail history</p>

            </div>
          </div>
        </div> -->
        <div class="col-lg-4 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <!-- <p class="text-center">Mandatory</p> -->
              <label for="inputState" id="form-label" class="form-label">Ticket Type :</label>
              <select class="form-select" aria-label="Default select example">
                <option selected>Choose...</option>
                <option>Wifi </option>
                <option>Printer</option>
                <option>Mail</option>
              </select><br>

              <label for="inputState" id="form-label" class="form-label">Sub Type :</label>
              <select id="inputState" class="form-select" name='ticketSubType' required>
                <option selected>Choose...</option>
                <option>Range</option>
                <option>Connectivity</option>
                <option>Wlan</option>
              </select><br>



              <label for="inputState" id="form-label" class="form-label">Issue Type :</label>
              <select id="inputState" class="form-select" name='ticketSubType' required>
                <option selected>Choose...</option>
                <option>Request</option>
                <option>Issue</option>
                <option>Major issue</option>
              </select><br>


              <label for="inputState" id="form-label" class="form-label">Priority :</label>
              <select name="priority" class="form-select" aria-label="Default select example">
                <option value="3" selected="">Choose...</option>
                <option value="Medium">Medium</option>
                <option value="High">High</option>
                <option value="Critical">Critical</option>
              </select>
              <br>



              <label for="inputState" id="form-label" class="form-label">Department :</label>
              <select class="form-select" aria-label="Default select example">
                <option selected>Choose...</option>
                <option>HR</option>
                <option>Admin</option>
                <option>Tech</option>
              </select><br>

            </div>
          </div>
        </div>


        <div class="col-lg-8 grid-margin stretch-card">
          <div class="card">
            {% for ticket in ticket_history  %}

            <div class="card-body">
                
              <h1 class="text-center mb-5">Ticket History</h1> 
           
                <div class="row mt-2 my-2" >
                  <div class="col">
                    <h6>Status :-</h6>
                  </div>
                  <div class="col">
                   <p>{{ticket.status}}</p>
                  </div>
                </div>
  
                <div class="row mt-2 my-2" >
                  <div class="col">
                    <h6>Created :-</h6>
                  </div>
                  <div class="col">
                   <p>{{ticket.created_at}}</p>
                  </div>
                </div>
  
                <div class="row mt-2 my-2" >
                  <div class="col">
                    <h6>Updated :-</h6>
                  </div>
                  <div class="col">
                   <p>{{ticket.updated_at}}</p>
                  </div>
                </div>
  
                <div class="row mt-2 my-2" >
                  <div class="col">
                    <h6>Assigned to :-</h6>
                  </div>
                  <div class="col">
                   <p>{{ticket.assigned_to}}</p>
                  </div>
                </div>
  
  
                <div class="row mt-2 my-2" >
                  <div class="col">
                    <h6>Assigned by :-</h6>
                  </div>
                  <div class="col">
                   <p>{{ticket.assigned_by}}</p>
                  </div>
                </div>
  
                <div class="row mt-2 my-2" >
                  <div class="col">
                    <h6>Completed at :-</h6>
                  </div>
                  <div class="col">
                   <p>{{ticket.completed_at}}</p>
                  </div>
                </div>
  
                <div class="row mt-2 my-2" >
                  <div class="col">
                    <h6>Time taken to resolve :-</h6>
                  </div>
                  <div class="col">
                   <p>{{ticket.time_to_resolve}}</p>
                  </div>
                </div>

             
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

templates/app/info.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Info Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body><hr>
    <div class="home_content home_contenthai">
        <div class="container-fluid cntnr p-5 m-5">
          <div class="row aline-center">
            <form action="{% url 'helpdeskapp:create_ticket' %}" method='post' enctype='multipart/form-data' class="p-3">
             
                <div class="form-group col-md-12">
                  <label for="inputtitle">Title</label>
                  <input type="title" class="form-control" id="title" placeholder="Title" name='title'>
                </div><br>
                <div class="form-group col-md-12">
                  <label for="exampleFormControlTextarea1">Description</label>
                  <textarea class="form-control" id="exampleFormControlTextarea1" rows="2" name='description'></textarea>
                </div><br>
              <div class="form-group col-md-12">
                <label for="inputtitle">Contact No</label>
                <input type="text" class="form-control" id="title" placeholder="Please Enter Your Phone number" name='contact_number'>
              </div><br>
  
              <select class="form-select" aria-label="Default select example">
                <option selected>Open this select menu</option>
                <option value="1">Low</option>
                <option value="2">Medium</option>
                <option value="3">High</option>
              </select><br>

              <div class="form-group col-md-12">
                <label for="inputState">Department</label>
                <select id="inputState" class="form-control" name='department'>
                  <option selected>Choose...</option>
                  <option>HR</option>
                  <option>Admin</option>
                  <option>Tech</option>
                </select>
              </div><br>
              <div class="form-group col-md-12">
                <label for="inputState">Ticket Type</label>
                <select id="inputState" class="form-control" name='ticketType'>
                  <option selected>Choose...</option>
                  <option>wifi </option>
                  <option>printer</option>
                  <option>mail</option>
                </select>
              </div><br>
              <div class="form-group col-md-12">
                <label for="inputState">Sub Type</label>
                <select id="inputState" class="form-control" name='ticketSubType'>
                  <option selected>Choose...</option>
                  <option>range</option>
                  <option>connectivity</option>
                  <option>wlan</option>
                </select>
              </div><br>              
              
              <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="inputCity">Attachment</label>
                  <input type="file" class="form-control" id="inputCity" placeholder="Your name.." name='attachment'>
                </div><br>
                
                <!-- <div class="ck">
                  <label for="inputck">Message</label>
                  <textarea cols="10" id="editor1" name="editor1" rows="10" >
                    &lt;p&gt;This is some &lt;strong&gt;sample text&lt;/strong&gt;. You are using &lt;a href="https://ckeditor.com/"&gt;CKEditor&lt;/a&gt;.&lt;/p&gt;
                  </textarea>
                </div><br> -->

                <div class="text-center">
                  <input class="btn btn-primary" type="submit" value="Submit">
                  <input class="btn btn-primary" type="reset" value="Reset">
                </div>
            </form>
            
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

templates/app/option.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>

    <h1>Select Ticket Category</h1>
    <br><br>
    <div class="row">
        <div class="col-sm-6 mb-3 mr-sm-0">
            <div class="card col-sm-8">
                <div class="card-body" id="op">
                    <a href="{% url 'helpdeskapp:index' %}" class="link">
                        <i class="fa fa-arrow-right fa-2x" aria-hidden="true">
                        General</i></a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card col-sm-8">
                <div class="card-body" id="op">
                    <a href="#" class="link">
                        <i class="fa fa-arrow-right fa-2x" aria-hidden="true">
                            Support</i></a>
                </div>
            </div>
        </div>
    </div><br>
    <div class="row">
        <div class="col-sm-6 mb-3 mr-sm-0">
            <div class="card col-sm-8">
                <div class="card-body" id="op">
                    <a href="#" class="link">
                        <i class="fa fa-arrow-right fa-2x" aria-hidden="true">
                            Advertising</i></a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card col-sm-8">
                <div class="card-body" id="op">
                    <a href="#" class="link">
                        <i class="fa fa-arrow-right fa-2x" aria-hidden="true">
                            Billing</i></a>
                </div>
            </div>
        </div>
    </div>
</center>
{% endblock %}

templates/app/update_User.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
  <style>
    .form-control{
      border: 1px solid #ced4da;
    }

    a{
      color: #6C63AC;
    }

  </style>
</head>
<div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      {% load crispy_forms_tags %}
      <form action="{% url 'helpdeskapp:update_ticket_User' ticket.id %}" method='post' class="p-3">
        {% csrf_token %}
        {{form_errors}}
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Update Ticket</h4>
              <form class="form-sample">
                <p class="card-description"> Give detail information of your ticket below </p>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.title|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <!-- <label class="col-sm-3 col-form-label">Title</label> -->
                      {{ form.department|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.ticketType|as_crispy_field }}
                  </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.ticketSubType|as_crispy_field }}
                   </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.priority|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                       {{ form.status|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.attachment|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">

                      {{ form.contact_number|as_crispy_field }}
                  
                    </div>
                  </div>
                </div>




                <div class="row">
                  <div class="col-md-12">

                    <div class="form-group ">

                      {{ form.description|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <button class="btn btn-outline-primary me-2 my-2">Reset</button>
                <button type="submit" class="btn btn-gradient-primary me-2 my-2">Submit</button>

              </form>
            </div>
          </div>
        </div>
    </div>
    </form>

  </div>

  <footer class="footer">
    <div class="container-fluid d-flex justify-content-between">
      <span class="text-muted d-block text-center text-sm-start d-sm-inline-block"><b>HelpDesk Ticketing System is Developed by Komal Sardar, Yashraj Chanchad & Suraj Kanade.<b></span>

    </div>
  </footer>
</div>

{% endblock %}