accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts import forms, views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

helpdeskapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from helpdeskapp import views


app_name = 'helpdeskapp'

urlpatterns = [
    path('',views.home, name='home'),
    path('login/', login_required(TemplateView.as_view(
        template_name='app/index.html')), name='index'),
    path('create-ticket/', views.create_ticket, name='create_ticket'),
    path('view-tickets/', views.ticket_list, name='ticket_list'),
    path('update-ticket/<pk>/', views.update_ticket_User, name='update_ticket_User'),
    path('change-ticket-status/', views.change_ticket_status, name='change_ticket_status'),
    path('grid/<int:pid>/', views.grid, name='grid'),
    path('edit/', views.edit, name='edit'),
    path('option/', views.option, name='option'),
    path('profile/', views.profile, name='profile'),
    path('welcome/',views.welcome,name='welcome'),
    path('history/<int:ticket_id>/',views.ticket_history,name='ticket_history'),
    path('updateRole/', views.updateRole , name="updateRole"),
    path('base/',views.base,name='base')
    
]
 

helpdeskweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdeskapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('engineer/', include('it_engineer.urls')),
    path('manager/', include('it_manager.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

it_manager/urls.py
from django.urls import path

from . import views


app_name = 'it_manager'

urlpatterns = [
    path('tickets/', views.ticket_list, name='ticket_list'),
    path('update_ticket_manager/<int:pk>', views.update_ticket_manager, name='update_ticket_manager'),
    path('manager-grid/<int:pid>/', views.manager_grid, name='manager_grid'),
    path('change-ticket-status/', views.change_ticket_status, name='change_ticket_status'),


    # path('grid/', views.grid, name='grid'),

]

templates/manager/managergrid.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
  #inline1,
  #inline2,
  #inline3,
  #inline4,
  #inline5,
  #inline6 {
    display: inline;
  }

  .btn {
    margin-top: 2rem;
  }

  .fa {

    color: #6C63AC;

    font-size: 22px;

  }

  @media(max-width:768px) {

    .ticketdetail {

      margin-top: 20px !important;

    }

  }

  .edit a {

    list-style: none;

    text-decoration: none;

    font-size: 1.1rem;

    color: #6C63AC;

  }

  .print a {

    list-style: none;

    font-size: 1.1rem;

    color: #6C63AC;

    text-decoration: none;

  }

  .dd {
    display: flex;

    justify-content: center;

    align-items: center;

    gap: 80px;
  }

  .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
    background-color: #6C63AC;
  }
</style>
<!-- partial -->
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title"> Ticket Details </h3>
      <!-- <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Forms</a></li>
            <li class="breadcrumb-item active" aria-current="page">Form elements</li>
          </ol>
        </nav> -->
    </div>
    <div class="row">
      <div class="col-md-8 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <form class="forms-sample">
              <div class="row">
                <div class="col-md-3">
                  <h6>Title :-</h6>
                </div>
                <div class="col-md-9">
                 <p>{{viewtickets.title}}</p>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3">
                  <h6>Description :- </h6>
                </div>
                <div class="col-md-9" >
                 <p>{{viewtickets.description}}</p>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3">
                  <h6>Contact :- </h6>
                </div>
                <div class="col-md-9" >
                 <p>{{viewtickets.contact_number}}</p>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!-- 
        <div class="col-md-4  grid-margin stretch-card">
          <div class="card">
             <div class="card-body d-flex justify-content-center align-items-center">
              <a id="editticket" href="{% url 'helpdeskapp:update_ticket_User' pk=viewtickets.id %}" title="Edit">
                <i class="fa fa-pencil-square-o ms- me-4" aria-hidden="true">&nbsp; &nbsp;Edit</i>
              </a>
              <span>

                <a href="#" onclick="window.print()" title="Print" target="_blank">
                  <i class="fa fa-print ms-5" aria-hidden="true">&nbsp; &nbsp;Print</i>
                </a>
              </span>
            </div> 
          </div>
        </div> -->


      <div class="col-md-4 mb-5">

        <div class="card">

          <div class="card-body d-flex justify-content-center align-items-center">
            <div class="dd">

              <div class="edit">




                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>

                <a id="editticket" href="{% url 'it_manager:update_ticket_manager' pk=viewtickets.id %}" title="Edit">
                  Edit

                </a>
              </div>
              <div class="print">

                <i class="fa fa-print" aria-hidden="true"></i>

                <a href="#" onclick="window.print()" title="Print" target="_blank">

                  Print
                </a>
              </div>

            </div>

          </div>

        </div>

      </div>

      <!-- <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Basic form elements</h4>
              <p class="card-description"> Basic form elements </p>
              <form class="forms-sample">
                <div class="form-group">
                  <label for="exampleInputName1">Name</label>
                  <input type="text" class="form-control" id="exampleInputName1" placeholder="Name">
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail3">Email address</label>
                  <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Email">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword4">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword4" placeholder="Password">
                </div>
                <div class="form-group">
                  <label for="exampleSelectGender">Gender</label>
                  <select class="form-control" id="exampleSelectGender">
                    <option>Male</option>
                    <option>Female</option>
                  </select>
                </div>
                <div class="form-group">
                  <label>File upload</label>
                  <input type="file" name="img[]" class="file-upload-default">
                  <div class="input-group col-xs-12">
                    <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
                    <span class="input-group-append">
                      <button class="file-upload-browse btn btn-gradient-primary" type="button">Upload</button>
                    </span>
                  </div>
                </div>
                <div class="form-group">
                  <label for="exampleInputCity1">City</label>
                  <input type="text" class="form-control" id="exampleInputCity1" placeholder="Location">
                </div>
                <div class="form-group">
                  <label for="exampleTextarea1">Textarea</label>
                  <textarea class="form-control" id="exampleTextarea1" rows="4"></textarea>
                </div>
                <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div> -->
      <div class="col-md-8 grid-margin">
        <div class="card pb-4">
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <h4 class="card-title">Add Reply</h4>
              <br><br>
              <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Message</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="comments"></textarea>
              </div>
              <br><br>
              <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="inputCity" id="form-label" class="form-label">Attachment :</label>
                  <input type="file" class="form-control" id="inputCity" placeholder="Your name.." name='attachment'>
                </div><br>
              </div>
              <input class="btn btn-primary" type="submit"  value="Submit">
 
          </div>
        </div>
        </form>
      </div>

      <div class="col-md-4 grid-margin  ticketdetails stretch-card" style="margin-top: -90px;">
        <div class="card ">
          <div class="card-body">
            <h4 class="card-title mb-5">Ticket Details</h4>
            <div class="boxR">


              <div class="row mt-2 my-2" >
                <div class="col">
                  <p>Ticket ID</p>
                </div>
                <div class="col">
                 <p>{{viewtickets.id}}</p>
                </div>
              </div>

              <div class="row my-3">
                <div class="col">
                  <p>Status </p>
                </div>
                <div class="col" >
                 <p>{{viewtickets.status}}</p>
                </div>
              </div>

            


              <div class="row my-2">
                <div class="col">
                  <p>Department </p>
                </div>
                <div class="col" >
                 <p>{{viewtickets.department}}</p>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <p> Priority </p>
                </div>
                <div class="col" >
                 <p>{{viewtickets.priority}}</p>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  {% if viewtickets.status == 'open' %}
              <form action="{% url 'it_manager:change_ticket_status' %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="closed" name="status">
                <input type="hidden" value="{{viewtickets.id}}" name="ticket_id">
                <button type="submit" class="btn btn-outline-danger">Close</button>
              </form>
              {% elif viewtickets.status == 'closed' %}
              <form action="{% url 'it_manager:change_ticket_status' %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="open" name="status">
                <input type="hidden" value="{{viewtickets.id}}" name="ticket_id">
                <button type="submit" class="btn btn-outline-success">Open Again</button>
              </form>
              {% else %}
              <button type="button" class="btn btn-primary text-white ">
                Work in progress..
              </button>
              {% endif %}
                </div>
             
              </div>

            </div>




          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->

        <!-- partial -->
      </div>
    </div>
    <!-- main-panel ends -->
  </div>



  {% endblock %}

templates/manager/ticket_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="main-panel">
  <div class="content-wrapper bg-white">
    <div class="boxes">
      <!-- <div class="filter" id="filter"> -->
      <!-- <button class="btn btn-primary my-3">All Tickets</button>
      <button class="btn btn-primary my-3">Open Tickets 0</button>
      <button class="btn btn-primary my-3">Close Tickets 0</button>
      <button class="btn btn-primary my-3">Resolved Tickets 0</button> -->

      <!-- </div> -->
    </div>
    <div class="table-responsive">
      <table id="test" class=" table-striped" style="width:100%">
        <thead>
          <tr style="background-color:  #9d96ce; color: white;">
            <th>Ticket Id</th>
            <th>Title</th>
            <th>Ticket Type</th>
            <th>Priority</th>
            <th>Department</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for ticket in tickets %}

          <tr>
            <td><a href="{% url 'it_manager:manager_grid' ticket.id %}"
                style="text-decoration: none; color: #6C63AC;">{{ticket.id}}</a></td>
            <td>{{ticket.title}}</td>
            <td>{{ticket.ticketType}}</td>
            <td>{{ticket.priority}}</td>
            <td>{{ticket.department}}</td>
            <td>{{ticket.status}}</td>


            <td>
              <div class="icons_list">
                <!-- view -->
                <li style="list-style:none;text-decoration: none;">
                  <a href="{% url 'it_manager:manager_grid' ticket.id %}">
                    <i class="fa-solid fa-eye" data-toggle="tooltip" data-placement="bottom" title="View"></i>
                  </a>
                </li>
                <!-- edit -->
                <li style="list-style:none;text-decoration: none;">
                  <a href="{% url 'it_manager:update_ticket_manager' pk=ticket.id %}">
                    <i class="fa-solid fa-pen-to-square" data-toggle="tooltip" data-placement="bottom" title="Edit"></i>
                  </a>
                </li>
                <!-- hestory -->
                <li style="list-style:none;text-decoration: none;">
                  <a href="{% url 'helpdeskapp:ticket_history' ticket.id  %}">
                    <i class="fa-solid fa-clock-rotate-left" data-toggle="tooltip" data-placement="bottom"
                      title="History"></i>
                  </a>
                </li>
              </div>
            </td>
          </tr>
          {% endfor %}

        </tbody>

      </table>
    </div>
  </div>

</div>


{% endblock %}

templates/manager/update_manager.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<head>
  <style>
    .form-control {
      border: 1px solid #ced4da;
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
      background-color: #6C63AC;
    }
    a{
      color:#6C63AC ;
    }
  </style>
</head>
<div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      {% load crispy_forms_tags %}
      <form action="{% url 'it_manager:update_ticket_manager' ticket.id %}" method='post' class="p-3">
        {% csrf_token %}
        {{form_errors}}
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Update Ticket</h4>
              <form class="form-sample">
                <p class="card-description"> Give detail information of your ticket below </p>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.title|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <!-- <label class="col-sm-3 col-form-label">Title</label> -->
                      {{ form.department|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.ticketType|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.ticketSubType|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.priority|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.status|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      {{ form.attachment|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">

                      {{ form.contact_number|as_crispy_field }}

                    </div>
                  </div>
                </div>




                <div class="row">
                  <div class="col-md-6">

                    <div class="form-group ">

                      {{ form.description|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-md-6">

                    <div class="form-group ">

                      {{ form.assign_to|as_crispy_field }}
                    </div>
                  </div>
                </div>
               
                <button class="btn btn-outline-primary me-2 my-2">Reset</button>
                <button type="submit" class="btn btn-gradient-primary me-2 my-2">Submit</button>

              </form>
            </div>
          </div>
        </div>
    </div>
    </form>

  </div>

  <footer class="footer">
    <div class="container-fluid d-flex justify-content-between">
      <span class="text-muted d-block text-center text-sm-start d-sm-inline-block"><b>HelpDesk Ticketing System is Developed by Komal Sardar, Yashraj Chanchad & Suraj Kanade.<b></span>


    </div>
  </footer>
</div>

{% endblock %}