accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts import forms, views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

helpdeskapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from helpdeskapp import views


app_name = 'helpdeskapp'

urlpatterns = [
    path('',views.home, name='home'),
    path('login/', login_required(TemplateView.as_view(
        template_name='app/index.html')), name='index'),
    path('create-ticket/', views.create_ticket, name='create_ticket'),
    path('view-tickets/', views.ticket_list, name='ticket_list'),
    path('update-ticket/<pk>/', views.update_ticket_User, name='update_ticket_User'),
    path('change-ticket-status/', views.change_ticket_status, name='change_ticket_status'),
    path('grid/<int:pid>/', views.grid, name='grid'),
    path('edit/', views.edit, name='edit'),
    path('option/', views.option, name='option'),
    path('profile/', views.profile, name='profile'),
    path('welcome/',views.welcome,name='welcome'),
    path('history/<int:ticket_id>/',views.ticket_history,name='ticket_history'),
    path('updateRole/', views.updateRole , name="updateRole"),
    path('base/',views.base,name='base')
    
]
 

helpdeskweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdeskapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('engineer/', include('it_engineer.urls')),
    path('manager/', include('it_manager.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

it_engineer/urls.py
from django.urls import path

from . import views


app_name = 'it_engineer'

urlpatterns = [
    path('tickets/', views.ticket_list, name='ticket_list'),
    path('update_ticket_Engineer/<int:pk>', views.update_ticket_Engineer, name='update_ticket_Engineer'),
    path('engineergrid/<int:pid>', views.engineergrid , name='engineergrid'),
    path('engineerhome/', views.engineerhome , name='engineerhome')
]

it_manager/urls.py
from django.urls import path

from . import views


app_name = 'it_manager'

urlpatterns = [
    path('tickets/', views.ticket_list, name='ticket_list'),
    path('update_ticket_manager/<int:pk>', views.update_ticket_manager, name='update_ticket_manager'),
    path('manager-grid/<int:pid>/', views.manager_grid, name='manager_grid'),
    path('change-ticket-status/', views.change_ticket_status, name='change_ticket_status'),


    # path('grid/', views.grid, name='grid'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HelpDesk</title>
    <!-- plugins:css -->
    <!-- "{% static 'css/demo.css' %}" -->
    <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' />



    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <script src="https://kit.fontawesome.com/e4f8bd703b.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    <style>
      li,label,h1,h2,h3,h4,h5,h6,p{
         font-family: "Poppins", sans-serif;
         font-size: 16px;
      }
    </style>
      <style>
        @import url(
         https://fonts.googleapis.com/css?family=Poppins+Sans);
        h1,h2,h3,h4,h5,h6{
            font-family: 'Poppins', serif;
            
        }
    </style>
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:../../partials/_navbar.html -->
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo" href=""><img src="{% static 'images/newlogo.jpg' %}" alt="logo" /></a>
          <a class="navbar-brand brand-logo-mini" href=""><img src="{% static 'images/logo-mini.svg' %}" alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
        
          <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item d-none d-lg-block full-screen-link">
              <a class="nav-link">
                <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
              </a>
            </li>
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                <div class="nav-profile-img">
                  <img src="{% static 'images/faces/face1.jpg' %}" alt="image">
                  <span class="availability-status online"></span>
                </div>
                <div class="nav-profile-text">
                  <p class="mb-1 text-black">{{first_name}}</p>
                </div>
              </a>
              <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
               
                <a class="dropdown-item" href="{% url 'accounts:logout'%}">
                  <i class="mdi mdi-logout me-2 menu-icon"></i> Signout </a>
              </div>
            </li>
          
            
         
          
         
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:../../partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item nav-profile">
              <a href="#" class="nav-link">
                <div class="nav-profile-image">
                  <img src="{% static 'images/faces/face1.jpg' %}" alt="profile">
                  <span class="login-status online"></span>
                  <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                  <span class="font-weight-bold mb-2">{{first_name}}</span>
                  <span class="text-secondary text-small">Project Manager</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
              </a>
            </li>
            <li class="nav-item">
                           {% if not request.user.is_it_engineer and not request.user.is_it_manager %}
              <a class="nav-link" href="{% url 'helpdeskapp:index' %}">
              {% endif %}
              {% if request.user.is_it_manager %} 
              <a class="nav-link" href="{% url 'it_manager:ticket_list'%}">
              {% endif %}
              {% if request.user.is_it_engineer %} 
              <a class="nav-link" href="{% url 'it_engineer:ticket_list'%}">
                {% endif %}
                <span class="menu-title">Home</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li>
      
            <li class="nav-item">
              {% if not request.user.is_it_engineer and not request.user.is_it_manager %}
              <a class="nav-link" href="{% url 'helpdeskapp:ticket_list'%}">
              {% endif %}
              {% if request.user.is_it_manager %} 
              <a class="nav-link" href="{% url 'it_manager:ticket_list'%}">
              {% endif %}
              {% if request.user.is_it_engineer %} 
              <a class="nav-link" href="{% url 'it_engineer:ticket_list'%}">
                {% endif %}

                <span class="menu-title">My Ticket</span>
                <i class="mdi mdi-ticket menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'helpdeskapp:profile' %}">
                <span class="menu-title">Profile</span>
                <i class="mdi mdi-contacts menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout'%}">
                <span class="menu-title">Log Out</span>
                <i class="mdi mdi-logout menu-icon"></i>
          
              </a>
            </li>
          <br>
          <br>
          <br>
            <img src="{% static 'images/3.png' %}" alt="" height="auto" width="60%" style="padding-left: 70px;">
        
          </ul>
        </nav>
        <!-- partial -->
        
        {% block content %} {% endblock %}
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="{% static 'vendors/js/vendor.bundle.base.js'  %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'js/off-canvas.js' %}"></script>
    <script src="{% static 'js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'js/misc.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="{% static 'js/file-upload.js' %}"></script>
    <!-- End custom js for this page -->
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    
    <script>
      $(document).ready(function() {
        $('#test').DataTable();
    } );
    </script>
  </body>
</html>

templates/home.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'landing/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="{% static 'landing/css/style.css' %}">
    <script src="https://kit.fontawesome.com/e4f8bd703b.js" crossorigin="anonymous"></script>
    <title>Help Desk</title>
    <style>
        body {
            overflow-y: hidden;
        }
        .btn{
            background-color:#6C63AC;
        }
    </style>
</head>
<body data-bs-spy="scroll" data-bs-target=".navbar" data-bs-offset="70">
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg py-3 sticky-top navbar-light bg-primary">
        <div class="container">
            <a class="navbar-brand" href="#">
                <!-- <img class="logo" src="img/logo-dark.svg" alt=""> -->
                <!-- <span class="logo">Cloudstrats</span> -->
                <img src="{% static 'images/3.png' %}" alt="" height="80px" width="500px">

            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <a class="ms-auto" href="{% url 'helpdeskapp:index' %}">
                    <button class="btn btn-outline-light ">LogIn</button>
                </a>
            </div>
        </div>
    </nav><!-- //NAVBAR -->

    <!-- HERO -->
    <div class="hero vh-100 d-flex align-items-center" id="home">
        <div class="container" style="margin-top: -120px;">
            <div class="row">
                <div class="col-lg-6 mx-auto text-center">
                    <h1 class="display-4 text-black mt-5">HelpDesk Support</h1>
                    <p class="text-black my-3">We offer premium support and
                        efficient solutions. Dynamically innovate resource-leveling customer service for state of the
                        art customer service.</p>
                    <!-- <a href="#" class="btn me-2 btn-primary">Get Started</a> -->
                    <!-- <a href="#" class="btn btn-outline-light">My Portfolio</a> -->
                </div>
                <div class="col-lg-3 col-sm-6">
                    <a href="{% url 'helpdeskapp:index' %}">
                        <div class="service card-effect my-3">
                            <div class="iconbox">
                                <i class="fa-solid fa-ticket"></i>
                            </div>
                            <h5 class="mt-4 mb-2">Add Ticket</h5>
                            <p>Create a new support ticket for a specific department </p>
                        </div>
                    </a></div>
                <div class="col-lg-3 col-sm-6">
                    <a href="{% url 'helpdeskapp:index' %}">
                        <div class="service card-effect my-3">
                            <div class="iconbox">
                                <i class="fa-solid fa-ticket"></i>
                            </div>
                            <h5 class="mt-4 mb-2">Existing Ticket</h5>
                            <p>View your past submitted tickets</p>
                        </div>
                    </a>

                </div>
            </div>
        </div>
    </div><!-- //HERO -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/info.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        .btn {
            width: 120px;
            height: 50px;
        }

        button {
            display: inline-block;
            text-align: center;
            text-decoration: none;
            margin: 20px;
            border: solid 1px transparent;
            border-radius: 4px;
            padding: 1rem 1.5rem;
            color: #FFFFFF;
            background-color: teal;
            cursor: pointer;
        }

        button:active {
            transform: translateY(1px);
            filter: saturate(150%);
        }

        button:hover {
            color: teal;
            border-color: currentColor;
            background-color: white;
        }

        button:focus {
            outline: none;
            box-shadow: 0 0 6px -2px teal;
        }

        #Action2 {
            background-color: tomato;
        }

        #Action2:active {
            transform: translateY(1px);
            filter: saturate(150%);
        }

        #Action2:hover {
            color: tomato;
            border-color: currentColor;
            background-color: white;
        }

        #Action2:focus {
            outline: none;
            box-shadow: 0 0 12px -2px tomato;
        }
    </style>
</head>

<body>

    <!-- <div class="box1 col-md-6">
        <h3>Name</h3>
        <div class="form-group">
            <label for="inputState">Priority</label>
            <select id="inputState" class="form-control" name='priority'>
                <option selected>Choose...</option>
                <option>low</i></option>
                <option>medium</i></option>
                <option>high</option>
            </select>
        </div><br>
        <div class="form-group col-md-12">
            <label for="inputtitle">Contact Field</label>
            <input type="title" class="form-control" id="title" placeholder="Title" name='title'>
        </div><br>
        <div class="form-group col-md-12">
            <label for="inputtitle">Contact Field</label>
            <input type="title" class="form-control" id="title" placeholder="Title" name='title'>
        </div><br>


        <textarea name="editor1">Type here and show console to see editor's height</textarea>
        <p class="text" style="display:none;">Show me or hide me when you desire</p>
        <button id="button">Click Me</button>
        <script src="cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script>

            CKEDITOR.replace('editor1');
            CKEDITOR.on('instanceReady', function (evt) {
                var editor = evt.editor;

                editor.on('change', function (e) {
                    var contentSpace = editor.ui.space('contents');
                    var ckeditorFrameCollection = contentSpace.$.getElementsByTagName('iframe');
                    var ckeditorFrame = ckeditorFrameCollection[0];
                    var innerDoc = ckeditorFrame.contentDocument;
                    var innerDocTextAreaHeight = $(innerDoc.body).height();
                    console.log(innerDocTextAreaHeight);
                });
            });


            $(document).ready(function () {
                $('#button').click(function () {
                    if ($('.text').is(':hidden')) {
                        $('.text').show();
                    } else {
                        $('.text').hide();
                    }
                });
            });
        </script>

</body>
</div>
</html> -->

templates/new.html
<form action="{% url 'helpdeskapp:updateRole' %}" method='post' class="p-3">
    {% csrf_token %}
    {{form_errors}}
{{form}}

<button type="submit" class="btn btn-gradient-primary me-2 my-2">Submit</button>

</form>

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<style>
  .initials {
    
    width: 100px;
    height: 100px;
    text-align: center;
    position: relative;
    border-top-left-radius: 50px;
    border-top-right-radius: 50px;
    border-bottom-left-radius: 50px;
    border-bottom-right-radius: 50px;
    margin: auto;
    border: 1px solid #7f30c0;

  }
  p{
    text-align: left;
  }
</style>



<div class="main-panel">
  <div class="content-wrapper">
    <div class="container" id="smp">
      <div class="row">
        <div class="col-md-4 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="box" id="bleft">

                <div class="initials" style="background-image: url(/static/images/faces/face1.jpg);">
                  
                </div>
                <div class="name mt-5" id="info">
                  <div class="row">
                    <!-- <div class="col-md-4">
                      <h6>Name :-</h6>
                    </div> -->
                    <div class="col-md-12 d-flex justify-content-center">
                      <p>{{first_name}} | {{last_name}}</p>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12 d-flex justify-content-center">
                      <p>{{email}} </p>
                    </div>
                  </div>


                 
                </div>

                <!-- <div class="button">
                  <button type="button" class="btn btn-primary ms-4">
                    Setting</button><br><br>
                  <button type="button" class="btn btn-primary">
                    Change Password</button>
                </div> -->
              </div>
            </div>
          </div>
        </div>
        <!-- </div></div> -->
        <div class="col-md-8 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="box" id="bright">
                <h1>User Information</h1><br>

                <div class="row">
                  <div class="col-md-4">
                    <h6>First Name </h6>
                  </div>
                  <div class="col-md-8">
                    <p>{{first_name}}</p>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-4">
                    <h6>Last Name </h6>
                  </div>
                  <div class="col-md-8">
                    <p>{{last_name}}</p>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-4">
                    <h6>Phone Number</h6>
                  </div>
                  <div class="col-md-8">
                    <p>{{phone_number}}</p>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-4">
                    <h6>Designation</h6>
                  </div>
                  <div class="col-md-8">
                    <p>{{Title}}</p>
                  </div>
                </div>
                
                <div class="row">
                  <div class="col-md-4">
                    <h6>Department</h6>
                  </div>
                  <div class="col-md-8">
                    <p>{{department}}</p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4">
                    <h6>City </h6>
                  </div>
                  <div class="col-md-8">
                    <p>{{city}}</p>
                  </div>
                </div>
           
              </div>


            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}