accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts import forms, views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

helpdeskapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from helpdeskapp import views


app_name = 'helpdeskapp'

urlpatterns = [
    path('',views.home, name='home'),
    path('login/', login_required(TemplateView.as_view(
        template_name='app/index.html')), name='index'),
    path('create-ticket/', views.create_ticket, name='create_ticket'),
    path('view-tickets/', views.ticket_list, name='ticket_list'),
    path('update-ticket/<pk>/', views.update_ticket_User, name='update_ticket_User'),
    path('change-ticket-status/', views.change_ticket_status, name='change_ticket_status'),
    path('grid/<int:pid>/', views.grid, name='grid'),
    path('edit/', views.edit, name='edit'),
    path('option/', views.option, name='option'),
    path('profile/', views.profile, name='profile'),
    path('welcome/',views.welcome,name='welcome'),
    path('history/<int:ticket_id>/',views.ticket_history,name='ticket_history'),
    path('updateRole/', views.updateRole , name="updateRole"),
    path('base/',views.base,name='base')
    
]
 

helpdeskweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdeskapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('engineer/', include('it_engineer.urls')),
    path('manager/', include('it_manager.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

it_engineer/urls.py
from django.urls import path

from . import views


app_name = 'it_engineer'

urlpatterns = [
    path('tickets/', views.ticket_list, name='ticket_list'),
    path('update_ticket_Engineer/<int:pk>', views.update_ticket_Engineer, name='update_ticket_Engineer'),
    path('engineergrid/<int:pid>', views.engineergrid , name='engineergrid'),
    path('engineerhome/', views.engineerhome , name='engineerhome')
]

it_manager/urls.py
from django.urls import path

from . import views


app_name = 'it_manager'

urlpatterns = [
    path('tickets/', views.ticket_list, name='ticket_list'),
    path('update_ticket_manager/<int:pk>', views.update_ticket_manager, name='update_ticket_manager'),
    path('manager-grid/<int:pid>/', views.manager_grid, name='manager_grid'),
    path('change-ticket-status/', views.change_ticket_status, name='change_ticket_status'),


    # path('grid/', views.grid, name='grid'),

]

templates/app/components/sidebar/it_engineer_sidebar.html
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div> <a href="#" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span
                    class="nav_logo-name">Help Desk</span> </a>
            <div class="nav_list">
                <a href="{% url 'helpdeskapp:index' %}" class="nav_link active"> <span class="material-symbols-outlined">
                    home
                    </span></i>
                    <span class="nav_name">Home</span> </a>
                <a href="{% url 'it_engineer:ticket_list' %}" class="nav_link"> <span class="material-symbols-outlined">
                    back_hand
                    </span></i>
                    <span class="nav_name">My Ticket</span> </a>

                <a href="#" class="nav_link"> <i class='bx bx-message-square-detail nav_icon'></i> <span
                        class="nav_name">Overview</span> </a>
            </div>
        </div> 
        <!-- <a href="{% url 'accounts:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span
                class="nav_name">SignOut</span> </a> -->
    </nav>
</div>

templates/app/components/sidebar/it_manager_sidebar.html
<!-- <div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div> <a href="#" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">Help
                    Desk</span> </a>
            <div class="nav_list">



                <a href="{% url 'helpdeskapp:index' %}" class="nav_link active"> <span
                        class="material-symbols-outlined">
                        home
                    </span></i>
                    <span class="nav_name">Home</span> </a>
                <a href="{% url 'it_manager:ticket_list' %}" class="nav_link"> <span class="material-symbols-outlined">
                        back_hand
                    </span></i>
                    <span class="nav_name">All Ticket</span> </a>
                <a href="" class="nav_link"> <span class="material-symbols-outlined">
                        back_hand
                    </span></i>
                    <span class="nav_name">ADD CUSTOMER</span> </a>
                <a href="" class="nav_link"> <span class="material-symbols-outlined">
                        back_hand
                    </span></i>
                    <span class="nav_name">ADD ENGINEER</span> </a>

                <a href="#" class="nav_link"> 
                    <i class='bx bx-message-square-detail nav_icon'></i> <span
                        class="nav_name">Overview</span> </a>
            </div>
        </div> 
        
    </nav>
</div> -->


<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="#" class="nav_logo">
                <span class="material-symbols-outlined">segment
                    <span class="nav_logo-name">Help Desk</span>
            </a>

            <div class="nav_list">

                <a href="{% url 'helpdeskapp:index' %}" class="nav_link"> <span class="material-symbols-outlined">
                        home
                    </span></i>
                    <span class="nav_name">Home</span></a>



                <a href="{% url 'it_manager:ticket_list' %}" class="nav_link"> <span class="material-symbols-outlined">
                        local_activity
                    </span>
                    <span class="nav_name">My Ticket</span> </a>


                    
                <a href="#" class="nav_link"> <i class='bx bx-layer nav_logo-icon'></i></i> <span
                        class="nav_name">Templates</span></a>

            </div>
        </div>
    </nav>
</div>

templates/app/components/sidebar/user_sidebar.html
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div> 
            <a href="#" class="nav_logo"> 
                <span class="material-symbols-outlined">segment
                <span class="nav_logo-name">Help Desk</span> 
            </a>

            <div class="nav_list">
                <a href="{% url 'helpdeskapp:welcome' %}" class="nav_link"> <span
                        class="material-symbols-outlined">
                        home
                    </span></i>
                    <span class="nav_name">Home</span></a>
                <a href="{% url 'helpdeskapp:ticket_list'%}" class="nav_link"> <span class="material-symbols-outlined">
                        local_activity
                    </span>
                    <span class="nav_name">My Ticket</span> </a>
                <a href="#" class="nav_link"> <i class='bx bx-layer nav_logo-icon'></i></i> <span
                        class="nav_name">Templates</span></a>
                <!-- <a href="#" class="nav_link"><span class="material-symbols-outlined">
                        library_books</span>                    
                    <span class="nav_name">Knowledgebase</span> </a> -->
                <!-- <a href="#" class="nav_link"> <span class="material-symbols-outlined">
                        category
                    </span> <span class="nav_name">Categories</span> </a>
                <a href="#" class="nav_link"> <span class="material-symbols-outlined">
                        groups
                    </span> <span class="nav_name">Team</span> </a>
                    <a href="#" class="nav_link"> <span class="material-symbols-outlined">
                        lab_profile
                        </span>
                    <span class="nav_name">Reports</span> </a>
                <a href="#" class="nav_link"> <span class="material-symbols-outlined">
                        view_module
                    </span> <span class="nav_name">Module</span> </a>
                <a href="#" class="nav_link"> <span class="material-symbols-outlined">tools_phillips</span> 
                    <span class="nav_name">Tools</span> </a>
                <a href="#" class="nav_link"> <i class='bx bx-message-square-detail nav_icon'></i> <span
                        class="nav_name">Settings</span> </a>
                <a href="#" class="nav_link"> <span class="material-symbols-outlined">settings</span> 
                    <span class="nav_name">Overview</span> </a> -->
            </div>
        </div>
    </nav>
</div>